services:

  postgres-db:
    image: postgres:16.3
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_USER: qweqweqeqe12312314
      POSTGRES_PASSWORD: qweqweqeqe12312314
      POSTGRES_DB: currency_exchange
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    networks:
      - app-network
    restart: always


  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6378:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass "redisCurrencyPasswordqwert12131"
    volumes:
      - cache:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  cache:
    driver: local

